# configuration file for dotnet-releaser
profile = "custom"
[msbuild]
project = "CS2DontBlindMe.sln"
[github]
user = "RIASorg"
repo = "CS2DontBlindMe"
[nuget]
publish = false
[brew]
publish = false
[scoop]
publish = false
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
