name: ci

on:
  push:
    paths-ignore:
    - '.gitattributes'
    - 'LICENSE'
    - 'changelog.md'
    - 'Readme.md'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build, Test, Pack, Publish
      shell: bash
      run: |
        dotnet tool install -g dotnet-releaser
        dotnet-releaser run --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml
